//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сerts
{
    public partial class CertsUser
    {
        public int Id { get; set; }
        public string fullName { get; set; }
        public string login { get; set; }
        public byte imageType { get; set; }
    }
}
